trigger:
  paths:
    include:
    - .azure-pipelines.yml

pool:
  vmImage: 'windows-latest'
steps:
- checkout: self
  fetchDepth: 1
- pwsh: '[System.Environment]::OSVersion.Version'
  displayName: test
