trigger:
  paths:
    include:
      - .azure-pipelines.yml

pool:
  vmImage: windows-latest

steps:
  - checkout: self
    fetchDepth: 1
  - pwsh: echo "$(Build.ArtifactStagingDirectory)"
    displayName: test
