contact_links:
- name: Translation / Localisation
  url: https://github.com/OpenRCT2/Localisation
  about: For localisation issues, go to the localisation repository.
- name: OpenRCT2 Discord Server
  url: https://discord.gg/ZXZd8D8
  about: For help with running or playing the game, join our Discord server.
